[package]
name = "uhidpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
nix = "0.26.1"
lazy_static = "1.4.0"
log = "0.4.17"
num_enum = "0.5.7"
